# Generated by Django 4.2.1 on 2023-05-08 10:52

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='descriptions',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
