# Generated by Django 4.2.1 on 2023-07-05 08:26

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
